# Generated by Django 3.1.13 on 2021-11-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211103_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(default='b', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='a', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
